---

# kb_plugins_reinstall will be set to true if kibana_install_from_repo.changed or kibana_install_from_package.changed
# i.e. we have changed KB version(or we have clean installation of KB), or if no plugins listed. Otherwise it is false and requires explicitly setting.
- name: set fact kb_plugins_reinstall to true
  set_fact: kb_plugins_reinstall=true
  when: (((debian_kibana_install_from_repo is defined and debian_kibana_install_from_repo.changed) or (redhat_kibana_install_from_repo is defined and redhat_kibana_install_from_repo.changed)) or (kibana_install_from_package is defined and kibana_install_from_package.changed)) or kb_plugins is not defined or kb_plugins is none

- name: set fact list_command
  set_fact: list_command=""
#If we are reinstalling all plugins, e.g. to a version change, we need to remove all plugins (inc. x-pack) to install any plugins. Otherwise we don't consider x-pack so the role stays idempotent.
- name: set fact list_command check for x-pack
  set_fact: list_command="| grep -vE 'x-pack'"
  when: not kb_plugins_reinstall

#List currently installed plugins. We have to list the directories as the list commmand fails if the KB version is different than the plugin version.
- name: Check installed kibana plugins
  become: yes
  shell: "ls {{kb_home}}/plugins {{list_command}}"
  register: installed_plugins
  changed_when: False
  ignore_errors: yes
  environment:
    CONF_DIR: "{{ conf_dir }}"
    KB_PATH_CONF: "{{ conf_dir }}"
    # KB_INCLUDE: "{{ instance_default_file }}"

#if kb_plugins_reinstall is set to true we remove ALL plugins
- name: set fact plugins_to_remove to install_plugins.stdout_lines
  set_fact: plugins_to_remove="{{ installed_plugins.stdout_lines | default([]) }}"
  when: kb_plugins_reinstall

#if the plugins listed are different than those requested, we remove those installed but not listed in the config
- name: set fact plugins_to_remove to delete plugins installed but not listed in kb_plugins
  set_fact: plugins_to_remove="{{ installed_plugins.stdout_lines | difference(kb_plugins | json_query('[*].plugin')) | default([]) }}"
  when: not kb_plugins_reinstall

#if kb_plugins_reinstall is set to true we (re)install ALL plugins
- name: set fact plugins_to_install to kb_plugins
  set_fact: plugins_to_install="{{ kb_plugins | json_query('[*].plugin') | default([]) }}"
  when: kb_plugins_reinstall

#if the plugins listed are different than those requested, we install those not installed but listed in the config
- name: set fact to plugins_to_install to those in kb_config but not installed
  set_fact: plugins_to_install="{{ kb_plugins | json_query('[*].plugin') | difference(installed_plugins.stdout_lines) | default([]) }}"
  when: not kb_plugins_reinstall

# This removes any currently installed plugins (to prevent errors when reinstalling)
- name: Remove kibana plugins
  become: yes
  command: "{{kb_home}}/bin/kibana-plugin remove {{item}} --silent"
  ignore_errors: yes
  with_items: "{{ plugins_to_remove | default([]) }}"
  notify: restart kibana
  register: plugin_removed
  environment:
    CONF_DIR: "{{ conf_dir }}"
    KB_PATH_CONF: "{{ conf_dir }}"
    # KB_INCLUDE: "{{ instance_default_file }}"

- name: Install kibana plugins
  become: yes
  command: "{{kb_home}}/bin/kibana-plugin install {{ item.plugin }} --batch --silent"
  register: plugin_installed
  failed_when: "'ERROR' in plugin_installed.stdout"
  changed_when: plugin_installed.rc == 0
  with_items: "{{ kb_plugins }}"
  when: item.plugin in plugins_to_install
  notify: restart kibana
  environment:
    CONF_DIR: "{{ conf_dir }}"
    KB_PATH_CONF: "{{ conf_dir }}"
    # KB_INCLUDE: "{{ instance_default_file }}"
    KB_JAVA_OPTS: "{% if item.proxy_host is defined and item.proxy_host != '' and item.proxy_port is defined and item.proxy_port != ''%} -Dhttp.proxyHost={{ item.proxy_host }} -Dhttp.proxyPort={{ item.proxy_port }} -Dhttps.proxyHost={{ item.proxy_host }} -Dhttps.proxyPort={{ item.proxy_port }}  {% elif kb_proxy_host is defined and kb_proxy_host != '' %} -Dhttp.proxyHost={{ kb_proxy_host }} -Dhttp.proxyPort={{ kb_proxy_port }} -Dhttps.proxyHost={{ kb_proxy_host }} -Dhttps.proxyPort={{ kb_proxy_port }} {% endif %}"
  until: plugin_installed.rc == 0
  retries: 5
  delay: 5

#Set permissions on plugins directory
- name: Set Plugin Directory Permissions
  become: yes
  file: state=directory path={{ kb_home }}/plugins owner={{ kb_user }} group={{ kb_group }} recurse=yes
