---

#Test if feature is installed
- name: Test if x-pack is installed
  shell: "{{kb_home}}/bin/kibana-plugin list | grep x-pack"
  become: true
  register: x_pack_installed
  changed_when: False
  failed_when: "'ERROR' in x_pack_installed.stdout"
  check_mode: no
  ignore_errors: yes
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_PATH_CONF: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"


#Remove X-Pack if installed and its not been requested or the KB version has changed
- name: Remove x-pack plugin
  become: true
  command: "{{kb_home}}/bin/kibana-plugin remove x-pack"
  register: xpack_state
  failed_when: "'ERROR' in xpack_state.stdout"
  changed_when: xpack_state.rc == 0
  when: x_pack_installed.rc == 0 and (not kb_enable_xpack or kb_version_changed)
  notify: restart kibana
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_PATH_CONF: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"


#Install plugin if not installed, or the kb version has changed (so removed above), and its been requested
- name: Download x-pack from url
  get_url: url={{ kb_xpack_custom_url }} dest=/tmp/x-pack-{{ kb_version }}.zip
  when: (x_pack_installed.rc == 1 or kb_version_changed) and (kb_enable_xpack and kb_xpack_custom_url is defined)

- name: Install x-pack plugin from local
  become: true
  command: >
    {{kb_home}}/bin/kibana-plugin install --silent file:///tmp/x-pack-{{ kb_version }}.zip
  register: xpack_state
  changed_when: xpack_state.rc == 70
  when: (x_pack_installed.rc == 1 or kb_version_changed) and (kb_enable_xpack and kb_xpack_custom_url is defined)
  notify: restart kibana
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_PATH_CONF: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"

- name: Delete x-pack zip file
  file: dest=/tmp/x-pack-{{ kb_version }}.zip state=absent
  when: kb_xpack_custom_url is defined

- name: Install x-pack plugin from elastic.co
  become: true
  command: >
    {{kb_home}}/bin/kibana-plugin install --silent x-pack
  register: xpack_state
  failed_when: "'ERROR' in xpack_state.stdout"
  changed_when: xpack_state.rc == 70
  when: (x_pack_installed.rc == 1 or kb_version_changed) and (kb_enable_xpack and kb_xpack_custom_url is not defined)
  notify: restart kibana
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_PATH_CONF: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"
    ES_JAVA_OPTS: "{% if kb_proxy_host is defined and kb_proxy_host != '' %}-Dhttp.proxyHost={{ kb_proxy_host }} -Dhttp.proxyPort={{ kb_proxy_port }} -Dhttps.proxyHost={{ kb_proxy_host }} -Dhttps.proxyPort={{ kb_proxy_port }}{% endif %}"

- name: Generate SSL/TLS environment
  include: ./kibana-xpack-ssl.yml